"""revision2

Revision ID: 0c4e7e01dc8c
Revises: 0f38ae6251a2
Create Date: 2023-02-01 17:33:22.857678

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0c4e7e01dc8c'
down_revision = '0f38ae6251a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
